/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedChecklistsIndexRouteImport } from './routes/_authenticated/checklists.index'
import { Route as AuthenticatedChecklistsIdRouteImport } from './routes/_authenticated/checklists.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChecklistsIndexRoute =
  AuthenticatedChecklistsIndexRouteImport.update({
    id: '/checklists/',
    path: '/checklists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChecklistsIdRoute =
  AuthenticatedChecklistsIdRouteImport.update({
    id: '/checklists/$id',
    path: '/checklists/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/checklists/': typeof AuthenticatedChecklistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/checklists': typeof AuthenticatedChecklistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/_authenticated/checklists/': typeof AuthenticatedChecklistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/checklists/$id' | '/checklists/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/checklists/$id' | '/checklists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/checklists/$id'
    | '/_authenticated/checklists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checklists/': {
      id: '/_authenticated/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checklists/$id': {
      id: '/_authenticated/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof AuthenticatedChecklistsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChecklistsIdRoute: typeof AuthenticatedChecklistsIdRoute
  AuthenticatedChecklistsIndexRoute: typeof AuthenticatedChecklistsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChecklistsIdRoute: AuthenticatedChecklistsIdRoute,
  AuthenticatedChecklistsIndexRoute: AuthenticatedChecklistsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
